// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProjectB.Migrations
{
    [DbContext(typeof(DataBaseConnection))]
    [Migration("20240530133556_AddReservationNumbers")]
    partial class AddReservationNumbers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<string>("ReservationNumber")
                        .HasColumnType("TEXT");

                    b.ToTable("Ticket");
                });

#pragma warning restore 612, 618
        }
    }
}
